### ISSUE TITLE
Current Version is not Compatible with the Latest LibRaw 0.16 [18 Jan 2014]

### ISSUE THREAD

**Issue by pmo-19** [mardy/qtraw#4] opened 2014-03-05 16:45 UTC
I first compiled libraw 0.16 and successfully made 4 Debian packages : libraw10, libraw-bin, libraw-dev, libraw-doc. Then I was trying to make a Debian package for qtraw, however I encountered the following error while compiling:

```../../src/raw-io-handler.cpp: In member function ‘bool RawIOHandlerPrivate::load(QIODevice*)’:
../../src/raw-io-handler.cpp:64:35: error: cannot allocate an object of abstract type ‘Datastream’
../../src/datastream.h:29:7: note:   because the following virtual functions are pure within ‘Datastream’:
/usr/local/include/libraw/libraw_datastream.h:63:20: note: 	virtual INT64 LibRaw_abstract_datastream::size()```

It looks like the C++ structures in both header files do not match.

from datastream.h [qtraw file] I get:

class Datastream: public LibRaw_abstract_datastream
{
public:
    Datastream(QIODevice *device);
    ~Datastream();

    // reimplemented virtual methods:
    virtual int valid();
    virtual int read(void *ptr, size_t size, size_t nmemb);
    virtual int seek(INT64 offset, int whence);
    virtual INT64 tell();
    virtual int get_char();
    virtual char *gets(char *s, int n);
    virtual int scanf_one(const char *fmt, void *val);
    virtual int eof();
    virtual void *make_jas_stream();

private:
    QIODevice *m_device;
};

from libraw_datastream.h [libraw file] I get:

class DllDef LibRaw_abstract_datastream
{
  public:
    LibRaw_abstract_datastream(){ substream=0;};
    virtual             ~LibRaw_abstract_datastream(void){if(substream) delete substream;}
    virtual int         valid() = 0;
    virtual int         read(void *,size_t, size_t ) = 0;
    virtual int         seek(INT64 , int ) = 0;
    virtual INT64       tell() = 0;
    virtual INT64 	size() = 0;	<------- Error here libraw_datastream.h:63:20: note: virtual INT64 LibRaw_abstract_datastream::size()
    virtual int         get_char() = 0;
    virtual char*       gets(char *, int) = 0;
    virtual int         scanf_one(const char *, void *) = 0;
    virtual int         eof() = 0;
    virtual void *      make_jas_stream() = 0;
    virtual int         jpeg_src(void *) { return -1; }
    /* Make buffer from current offset */

    /* subfile parsing not implemented in base class */
    virtual const char* fname(){ return NULL;};
#if defined(_WIN32) && !defined(__MINGW32__) && defined(_MSC_VER) && (_MSC_VER > 1310)
	virtual const wchar_t* wfname(){ return NULL;};
	virtual int         subfile_open(const wchar_t*) { return -1;}
#endif
    virtual int         subfile_open(const char*) { return -1;}
    virtual void        subfile_close() { }


    virtual int		tempbuffer_open(void*, size_t);
    virtual void	tempbuffer_close();

  protected:
    LibRaw_abstract_datastream *substream;
};

Also I am not a specialist of C++ ... Will you update the code for qtraw or make a new branch compatible with the code I see from LibRaw 0.16 ?

Thanks.

**Comment by vrabeux** [comment] 2015-02-27 21:29
Hi,

I am trying to use this branch (libraw-0.16) but I get the following error :
``` 
Decoding raw data
unknown file: data corrupted at 4237501
``` 
Here is the files I am using :
http://www.mannyphoto.com/D700D3/

Any idea ?

Thanks a lot,

Vincent.

**Comment by mike-pt** [comment] 2015-03-08 02:49
FYI this failed for me on FreeBSD, but "libraw-0.16libraw-0.16""works... 

As a side-note on FreeBSD I add to remove tests:
```
cd tests/ && ( test -e Makefile || /usr/local/lib/qt5/bin/qmake /usr/home/miguelc/gitstuff/qtraw/tests/tests.pro PREFIX=/usr/local/ LIBDIR=/usr/local/lib QT5LIBDIR=/usr/local/lib/qt5 -o Makefile ) && make -f Makefile
clang++ -c -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE -fPIE -DQT_NO_DEBUG -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/usr/home/miguelc/gitstuff/qtraw/tests\" -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I. -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtTest -isystem /usr/local/include/qt5/QtGui -isystem /usr/local/include/qt5/QtCore -I. -o qtraw-test.o qtraw-test.cpp
/usr/local/lib/qt5/bin/moc -DQT_NO_DEBUG -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/usr/home/miguelc/gitstuff/qtraw/tests\" -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I/usr/home/miguelc/gitstuff/qtraw/tests -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtTest -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I/usr/local/include -I/usr/include/c++/v1 -I/usr/include/clang/3.5.1 -I/usr/include qtraw-test.h -o moc_qtraw-test.cpp
clang++ -c -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE -fPIE -DQT_NO_DEBUG -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/usr/home/miguelc/gitstuff/qtraw/tests\" -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I. -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtTest -isystem /usr/local/include/qt5/QtGui -isystem /usr/local/include/qt5/QtCore -I. -o moc_qtraw-test.o moc_qtraw-test.cpp
clang++ -pthread -Wl,-rpath,/usr/local/lib -o qtraw-test qtraw-test.o  moc_qtraw-test.o   -lQt5Test -lQt5Gui -lQt5Core -lGL
/usr/bin/ld: cannot find -lQt5Test
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

clang flags seem correct for moc_qtraw-test but not qtraw-test

**Comment by mardy** [comment] 2015-03-08 07:31
This is now merged in master.

Thanks Vincent for notifying me of the decoding problem; I've a Sony camera myself, and I didn't run into that issue. But it should now be fixed, I could successfully load both a NEF and a CR2 file.

Mike, the build flags seem correct to me; do you have a libQt5Test.* in /usr/local/lib? Maybe you did not install it.

**Closed by mardy** 2015-03-08 07:31 UTC

**Comment by mike-pt** [comment] 2015-03-08 21:59
@mardy Yes libQt5Test is installed:

```
% sudo pkg info | grep testlib
qt5-testlib-5.3.2              Qt unit testing module


% sudo pkg info -l qt5-testlib |grep so
	/usr/local/lib/libQt5Test.so
	/usr/local/lib/libQt5Test.so.5
	/usr/local/lib/libQt5Test.so.5.3
	/usr/local/lib/libQt5Test.so.5.3.2
```

I can just leave the tests out of the build, but it might be best to till investigate why this happens and open a new GHI.

NOTE: About the flags note that the include_path is not even there:
```
clang++ -c -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE -fPIE -DQT_NO_DEBUG -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/usr/home/miguelc/gitstuff/qtraw/tests\" -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I. -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtTest -isystem /usr/local/include/qt5/QtGui -isystem /usr/local/include/qt5/QtCore -I. -o qtraw-test.o qtraw-test.cpp
/usr/local/lib/qt5/bin/moc -DQT_NO_DEBUG -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/usr/home/miguelc/gitstuff/qtraw/tests\" -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I/usr/home/miguelc/gitstuff/qtraw/tests -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtTest -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtCore -I/usr/local/include -I/usr/include/c++/v1 -I/usr/include/clang/3.5.1 -I/usr/include qtraw-test.h -o moc_qtraw-test.cpp
```
[All good here]

```
clang++ -c -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE -fPIE -DQT_NO_DEBUG -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/usr/home/miguelc/gitstuff/qtraw/tests\" -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I. -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtTest -isystem /usr/local/include/qt5/QtGui -isystem /usr/local/include/qt5/QtCore -I. -o moc_qtraw-test.o moc_qtraw-test.cpp
```
[All good here]

```
clang++ -pthread -Wl,-rpath,/usr/local/lib -o qtraw-test qtraw-test.o  moc_qtraw-test.o   -lQt5Test -lQt5Gui -lQt5Core -lGL
```
[But not here... ]

**Comment by mardy** [comment] 2015-03-09 07:20
Mike, the last command it about linking the compiled files together, it's not about compiling: so, it's perfectly normal that there include paths are not specified.
One thing that might be the cause for the failure is that you have installed Qt in /usr/local/lib, and not in /usr/lib; therefore, you need to instruct the linker to look for the libraries in there. Try to set the variable LIBRARY_PATH=/usr/local/lib before running make, that might help.

**Comment by mike-pt** [comment] 2015-03-09 16:13
You're correct of course. Its the linking that's faling and the others are part of compilation and worked fine, because the include path is set.

Its the library_path that's probably hardcode for the usual linux path, in freebsd 3rd party packages and libs go to "/usr/local/...." no "/usr/.."

I was assuming setting LIBDIR (which I set to PREFIX/lib and PREFIX is /usr/local) woudl do it, but maybe not?


I also notice "target.path += $$[QT_INSTALL_PLUGINS]" which I should set. In FreeBSD it would be "/usr/local/lib/qt5/plugins/"

**Comment by mike-pt** [comment] 2015-03-09 17:32
Actually I think I found what's going on... src/Makefile adds "-L /usr/local/lib" but test/Makefile doens't

I don't know that much about qt much less .pro files... but I noticed tests doens't use the "lib" TEMPLATE, maybe that's the cause?
Or I guess this could still be added by setting LIB += -L/usr/local/lib

But due to my inexperience with qt, I'm not sure what's the best thing to do, or even if I'm making sense here...

For now I did it like this:
```
 git diff
diff --git a/tests/tests.pro b/tests/tests.pro
index ba685ad..38e0e08 100644
--- a/tests/tests.pro
+++ b/tests/tests.pro
@@ -2,6 +2,8 @@ include(../common-config.pri)
 
 TARGET = qtraw-test
 
+LIBS += -L/usr/local/lib
+
 QT += \
     testlib
```

Then:
```
/usr/local/lib/qt5/bin/qmake PREFIX=/usr/local LIBDIR=/usr/local/lib QT_INSTALL_PLUGINS=/usr/local/lib/qt5/plugins/ qtraw.pro

make

make install
```
[Done]
